apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: optimizely-cmsv2
  name: optimizely-cmsv2
  namespace: kingdroid-ns
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: optimizely-cmsv2
  template:
    metadata:
      labels:
        app: optimizely-cmsv2
    spec:
      containers:
        - name: optimizely-v2
          image: registry.digitalocean.com/test-docr/optimizely-v2:{{github_sha}}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "500m"
            requests:
              memory: "60Mi"
              cpu: "250m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: optimizely
  namespace: kingdroid-ns
spec:
  type: NodePort
  selector:
    app: optimizely-cmsv2
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  sessionAffinity: None
  externalTrafficPolicy: Local