name: Digital Ocean Deploy Workflow

on:
  push:
    branches: ["main"]

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t optimizely-v2:${{ github.sha }} .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag optimizely-v2:${{ github.sha }} registry.digitalocean.com/test-docr/optimizely-v2:${{ github.sha }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/test-docr/optimizely-v2:${{ github.sha }}

  deploy-to-DO-Kubernetes:
    runs-on: ubuntu-latest
    needs: build-push-docker-image
    steps:
      - uses: actions/checkout@v3
      # Set up the Kubernetes CLI with your DigitalOcean Kubernetes cluster.
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: test-cluster01
          expirationTime: "1200"

      # Apply kubernetes manifests
      - name: Update And Apply Kubernetes manifest file
        run: |
          cat $GITHUB_WORKSPACE/k8s/deployment.yml | sed "s/{{github_sha}}/${{ github.sha }}/g" | \
          kubectl apply -f -
